# -*- coding: utf-8 -*-
"""2024_0315_Estadisticos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1118U350Qhl0FEt29jzqoCO6GAs4fd742
"""

from math import sqrt

v = [178, 183, 170, 179, 175 , 186]

def promedio(v):
    k = len(v)
    acomulador = 0
    for i in range(k):
        acomulador = v[i] + acomulador
    promedio = acomulador / k
    return promedio

print("El promedio para la lista es",promedio(v))

def desv_est(v):
    k = len(v)
    prom = promedio(v)
    acomulador = 0
    for i in range(k):
        acomulador = (v[i] - prom)**2 + acomulador
    desv_est = (acomulador / (k-1))
    return desv_est

print("La desviacion estandar para la lista es",desv_est(v))

def varianza(v):
    desv = desv_est(v)
    var = desv ** 2
    return var

print("La varianza para la lista es",varianza(v))