# -*- coding: utf-8 -*-
"""Quiz2Correccion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qFPi5B79hY_TRqf14ssGRlW2BTxvcXfe
"""

class Matrix:
    def __init__(self, data, m, n):
        self.data = data
        self.m = m
        self.n = n

    def getelem(self, i, j):
        return self.data[i][j]


#Para evaluar el funcionamiento de nuestra definicion para la multiplicacion de matrices entonces tenemos:

#Definimos la matriz self
self_data = [[1, 2],
             [3, 4]]
self_matrix = Matrix(self_data, 2, 2)

#Definimos la matriz B
B_data = [[5, 6],
          [7, 8]]
B_matrix = Matrix(B_data, 2, 2)


def mat_mult(self, B):
    salida = []
    for i in range(self.m):
        fila = []
        for j in range(B.n):
            acum = 0
            for k in range(self.n):
                acum += self.getelem(i, k) * B.getelem(k, j)
            #fila.append(acum)
        #salida.append(fila)
            salida.append(acum)
    return salida


# Multiplicar las matrices usando tu función
Matriz_Resultante = mat_mult(self_matrix, B_matrix)


# Imprimir el resultado
print("El resultado de la multiplicación en forma de lista es:")
print(Matriz_Resultante)